More QA, constrain gcc install from fedora repo

diff --git a/install_tmcstu b/install_tmcstu
--- a/install_tmcstu
+++ b/install_tmcstu
@@ -38,14 +38,16 @@ function install_pyenv() {
 }
 
 function install_config_tools() {
-  sudo dnf -y install make cmake autoconf automake git binutils binutils-devel\
-                gcc gfortran gcc-c++ \
-                bzip2 gzip p7zip \
-                environment-modules \
-                vim-enhanced neovim \
-                jq \
-                ripgrep fd-find \
-                lshw htop
+  # since CUDA incompatiblity may happen for GCC, use the stable version instead of update
+  sudo dnf --enablerepo=fedora -y install \
+    make cmake autoconf automake git binutils binutils-devel \
+    gcc gfortran gcc-c++ \
+    bzip2 gzip p7zip \
+    environment-modules \
+    vim-enhanced neovim \
+    jq \
+    ripgrep fd-find \
+    lshw htop
 }
 
 function install_network_tools() {
@@ -111,11 +113,12 @@ function install_cuda() {
 
   # install kernel headers
   sudo dnf install "kernel-devel-$(uname -r)" "kernel-headers-$(uname -r)"
-  # disable the nvidia-driver if existing
-  # https://ask.fedoraproject.org/t/dnf-update-nvidia-error/8864/5
-  # https://rpmfusion.org/Howto/CUDA#Which_driver_Package
+  # add official repo
   sudo dnf config-manager --add-repo \
     "https://developer.download.nvidia.com/compute/cuda/repos/fedora$FEDORA_VERSION/x86_64/cuda-fedora$FEDORA_VERSION.repo"
+  # disable the nvidia-driver if existing, according to
+  # https://ask.fedoraproject.org/t/dnf-update-nvidia-error/8864/5
+  # https://rpmfusion.org/Howto/CUDA#Which_driver_Package
   sudo dnf clean expire-cache
   sudo dnf -y module disable nvidia-driver
   sudo dnf -y install cuda
@@ -137,7 +140,9 @@ function verify_cuda() {
   fi
   cwd="$(pwd)"
   cd NVIDIA_CUDA-"$CUDA_VERSION"_Samples || exit 0
-  make
+  make || \
+    echo "If c++:chrono error happens in make, try downgrade gcc by: dnf downgrade gcc. 10.0.1 and 10.2.1 shall work." \
+    && exit 1
   cd bin/x86_64/linux/release || exit 0
   ./deviceQuery
   # this binary detects workable CUDA-GPU
